language: python

python:
    - 2.7
    - 3.6

before_install:
    - pwd
    - date -u
    - uname -a
    - lsb_release -a
    - sudo apt-get -qq update
    - sudo apt-get install build-essential python-dev swig libasound2-dev

install:
    - pip install codecov
    - python setup.py install

script:
    - coverage run setup.py tests

after_success:
   - cd ..
  - bash <(curl -s https://codecov.io/bash)
